### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

In [1]:
import numpy as np
from random import randint

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero por defecto a utilizar, que en un futuro será configurable.

In [2]:
T = np.array([[8,7,6],
              [3,2,5],
              [0,1,4]])
print(T)

[[8 7 6]
 [3 2 5]
 [0 1 4]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero.

In [3]:
R = np.array([[-1,0,0,0,-1,-1,-1,-1,-1],
              [0,-1,0,0,0,0,-1,-1,-1],
              [0,0,-1,0,0,0,100,0,0],
              [0,0,0,-1,-1,-1,-1,0,0],
              [-1,0,0,-1,-1,0,-1,-1,-1],
              [-1,0,0,-1,0,-1,100,0,-1],
              [-1,-1,0,-1,-1,0,100,0,-1],
              [-1,-1,0,0,-1,0,100,-1,0],
              [-1,-1,0,0,-1,-1,-1,0,-1]])
print(R)

[[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]


## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [4]:
Q = np.zeros((9,9))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [5]:
inicio = 0
objetivo = 6
episodios = 10000
gamma = 0.8
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")

La celda de inicio será la 0 y la celda objetivo será la 6.
El número de episodios será 10000 y el factor de aprendizaje gamma será de 0.8.


## Algoritmo
La ejecución del algoritmo.

In [6]:
rango = range(episodios)

for x in rango:
    inicio = randint(0, 8)
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    actual = inicio
    while actual != objetivo:
        posibles = []
        for y in range(9):
            if R[actual][y] == 0 or R[actual][y] == 100:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        aleatorioPosibles = randint(0,int(len(posibles)-1))
        aleatorio = posibles[aleatorioPosibles]
        print("Se elige aleatoriamente la celda " + str(aleatorio) + ".")
        supuestos = []
        for z in range(9):
            if R[aleatorio][z] == 0 or R[aleatorio][z] == 100:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        maximoSupuestos = max(supuestos)
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    print("Se alcanza la celda objetivo.")

ista de siguientes celdas posibles es: [0, 1, 3, 4, 5, 6, 7, 8]
Se elige aleatoriamente la celda 5.
Se actualiza el valor de Q[2][5] a 80.0.
Actualizamos la celda actual a 5.
La lista de siguientes celdas posibles es: [1, 2, 4, 6, 7]
Se elige aleatoriamente la celda 6.
Se actualiza el valor de Q[5][6] a 100.0.
Actualizamos la celda actual a 6.
Se alcanza la celda objetivo.

Episodio 9992: Se establece 4 como celda de inicio, y se toma como celda objetivo la 6.
La lista de siguientes celdas posibles es: [1, 2, 5]
Se elige aleatoriamente la celda 5.
Se actualiza el valor de Q[4][5] a 80.0.
Actualizamos la celda actual a 5.
La lista de siguientes celdas posibles es: [1, 2, 4, 6, 7]
Se elige aleatoriamente la celda 4.
Se actualiza el valor de Q[5][4] a 64.0.
Actualizamos la celda actual a 4.
La lista de siguientes celdas posibles es: [1, 2, 5]
Se elige aleatoriamente la celda 2.
Se actualiza el valor de Q[4][2] a 80.0.
Actualizamos la celda actual a 2.
La lista de siguientes celdas posible

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [7]:
print(Q)

[[  0.  64.  80.  64.   0.   0.   0.   0.   0.]
 [ 64.   0.  80.  64.  64.  80.   0.   0.   0.]
 [ 64.  64.   0.  64.  64.  80. 100.  80.  64.]
 [ 64.  64.  80.   0.   0.   0.   0.  80.  64.]
 [  0.  64.  80.   0.   0.  80.   0.   0.   0.]
 [  0.  64.  80.   0.  64.   0. 100.  80.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  80.  64.   0.  80. 100.   0.  64.]
 [  0.   0.  80.  64.   0.   0.   0.  80.   0.]]


## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 debería ser 0, 2, 6.

In [8]:
inicio = 0
objetivo = 6
camino = []
camino.append(inicio)
actual = inicio
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
print(camino)


[0, 2, 6]
