### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

In [771]:
import time
import numpy as np
import random
from random import randint
np.set_printoptions(threshold=sys.maxsize)

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero a utilizar, que por defecto será de 36 por 36 y los movimientos posibles se basan en los del caballo en el juego del ajedrez.

In [772]:
T = np.array([[35,34,33,32,31,30],
              [24,23,22,21,20,29],
              [15,14,13,12,19,28],
              [8,7,6,11,18,27],
              [3,2,5,10,17,26],
              [0,1,4,9,16,25]])
print(T)

[[35 34 33 32 31 30]
 [24 23 22 21 20 29]
 [15 14 13 12 19 28]
 [ 8  7  6 11 18 27]
 [ 3  2  5 10 17 26]
 [ 0  1  4  9 16 25]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero.

In [773]:
R = np.full((36,36),-1)
R[0][5] = 1
R[0][7] = 0
R[1][6] = 0
R[1][8] = 0
R[1][10] = 0
R[2][9] = 0
R[2][11] = 0
R[2][13] = 0
R[2][15] = 0
R[3][4] = 0
R[3][6] = 0
R[3][14] = 0
R[4][3] = 0
R[4][7] = 0
R[4][11] = 0
R[4][17] = 0
R[5][0] = 0
R[5][8] = 0
R[5][12] = 0
R[5][14] = 0
R[5][16] = 0
R[5][18] = 5
R[6][1] = 0
R[6][3] = 0
R[6][15] = 0
R[6][16] = 0
R[6][18] = 5
R[6][19] = 0
R[6][21] = 10
R[6][23] = 0
R[7][0] = 0
R[7][4] = 0
R[7][10] = 0
R[7][12] = 0
R[7][22] = 0
R[7][24] = 0
R[8][1] = 0
R[8][5] = 1
R[8][13] = 0
R[8][23] = 0
R[9][2] = 0
R[9][6] = 0
R[9][18] = 5
R[9][26] = 0
R[10][1] = 0
R[10][7] = 0
R[10][13] = 0
R[10][19] = 0
R[10][25] = 0
R[10][27] = 0
R[11][2] = 0
R[11][4] = 0
R[11][14] = 0
R[11][16] = 0
R[11][20] = 0
R[11][22] = 0
R[11][26] = 0
R[11][28] = 0
R[12][5] = 1
R[12][7] = 0
R[12][17] = 0
R[12][23] = 0
R[12][27] = 0
R[12][29] = 0
R[12][31] = 0
R[12][33] = 0
R[13][2] = 0
R[13][8] = 0
R[13][10] = 0
R[13][18] = 5
R[13][20] = 0
R[13][24] = 0
R[13][32] = 0
R[13][34] = 0
R[14][3] = 0
R[14][5] = 1
R[14][11] = 0
R[14][21] = 10
R[14][33] = 0
R[14][35] = 0
R[15][2] = 0
R[15][6] = 0
R[15][22] = 0
R[15][34] = 0
R[16][5] = 1
R[16][11] = 0
R[16][27] = 0
R[17][4] = 0
R[17][6] = 0
R[17][12] = 0
R[17][28] = 0
R[18][5] = 1
R[18][9] = 0
R[18][13] = 0
R[18][21] = 10
R[18][25] = 0
R[18][29] = 0
R[19][6] = 0
R[19][10] = 0
R[19][22] = 0
R[19][26] = 0
R[19][30] = 100
R[19][32] = 0
R[20][11] = 0
R[20][13] = 0
R[20][27] = 0
R[20][33] = 0
R[21][6] = 0
R[21][14] = 0
R[21][18] = 5
R[21][28] = 0
R[21][30] = 100
R[21][34] = 0
R[22][7] = 0
R[22][11] = 0
R[22][15] = 0
R[22][19] = 0
R[22][31] = 0
R[22][35] = 0
R[23][6] = 0
R[23][8] = 0
R[23][12] = 0
R[23][32] = 0
R[24][7] = 0
R[24][13] = 0
R[24][33] = 0
R[25][10] = 0
R[25][18] = 5
R[26][9] = 0
R[26][11] = 0
R[26][19] = 0
R[27][10] = 0
R[27][12] = 0
R[27][16] = 0
R[27][20] = 0
R[28][11] = 0
R[28][17] = 0
R[28][21] = 10
R[28][31] = 0
R[29][12] = 0
R[29][18] = 5
R[29][32] = 0
R[30][30] = 100
R[30][19] = 0
R[30][21] = 10
R[31][12] = 0
R[31][22] = 0
R[31][28] = 0
R[32][13] = 0
R[32][19] = 0
R[32][23] = 0
R[32][29] = 0
R[33][12] = 0
R[33][14] = 0
R[33][20] = 0
R[33][24] = 0
R[34][13] = 0
R[34][15] = 0
R[34][21] = 10
R[35][14] = 0
R[34][22] = 0
print(R)

[[ -1  -1  -1  -1  -1   1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1   0  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1   0  -1   0  -1   0  -1   0  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1   0  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1   0  -1  -1  -1   0  -1  -1  -1   0  -1  -1  -1  -1  -1   0
   -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0  -1  -1  -1  -1  -1  -1  -1   0  -1  -1  -1   0  -1   0  -1   0  -1
    5  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   0   0  -1
    5   0  -1  10  -1   0  -1  -

## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [774]:
Q = np.zeros((36,36))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.

## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [775]:
inicio = 0
objetivo = 30
episodios = 1000
gamma = 0.9
epsilon = 0
alpha = 0
tamano = 36 # Número total de casillas de la matriz
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")
print("El valor de épsilon es " + str(epsilon) + " y el de alpha es " + str(alpha) + ".")

La celda de inicio será la 0 y la celda objetivo será la 30.
El número de episodios será 1000 y el factor de aprendizaje gamma es de 0.9.
El valor de épsilon es 0 y el de alpha es 0.


## Algoritmo
La ejecución del algoritmo.

In [776]:
#Iniciamos el contador de tiempo para medidas de rendimiento
start = time.time()

rango = range(episodios)

for x in rango:
    inicio = randint(0, tamano-1)
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    actual = inicio
    while actual != objetivo:
        posibles = []
        for y in range(tamano):
            if R[actual][y] != -1:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        # Implementación epsilon fase 2
        aleatorioEpsilon = random.uniform(0,1)

        # Si el valor aleatorio es menor que epsilon
        if aleatorioEpsilon < epsilon:
            # Elegimos aleatoriamente el estado siguiente
            aleatorioPosibles = randint(0,int(len(posibles)-1))
            aleatorio = posibles[aleatorioPosibles]
            print("El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: " + str(aleatorio) + ".")
        # Si el valor aleatorio es mayor que epsilon
        else:
            posiblesValor = []
            for posible in posibles:
                supuestosPosible = []
                # Analizamos cuales son las celdas viables segun la matriz R
                for aux in range(tamano):
                    if R[posible][aux] != -1:
                        # Calculamos el valor de dicha celda en nuestra matriz Q
                        valor = Q[posible][aux]
                        supuestosPosible.append(valor)
                # Seleccionamos la celda con mayor valor en nuestra matriz
                maximoSupuestosPosible = max(supuestosPosible)
                posiblesValor.append(R[actual][posible] + gamma * maximoSupuestosPosible)
            aleatorio = posibles[np.argmax(posiblesValor)]
            print("El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: " + str(aleatorio) + ".")
        ##---------------------
        supuestos = []
        for z in range(tamano):
            if R[aleatorio][z] != -1:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        maximoSupuestos = max(supuestos)
        # Actualizamos el valor de Q segun los estados seleccionados
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    # Actualizamos el valor de Q para la celda objetivo
    Q[actual][actual] = R[actual][actual] + gamma * Q[actual][actual]
    # Actualizamos el valor de epsilon en base al alpha definido y repetimos la iteracion hasta el ultimo episodio
    epsilon = epsilon * alpha
    print("Se actualiza el valor de épsilon a " + str(epsilon) + ".")
    print("Se alcanza la celda objetivo.")

#Finalizamos el contador de tiempo para medidas de rendimiento
end = time.time()

La lista de siguientes celdas posibles es: [6, 14, 18, 28, 30, 34]
El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: 30.
Se actualiza el valor de Q[21][30] a 999.9999999999997.
Actualizamos la celda actual a 30.
Se actualiza el valor de épsilon a 0.
Se alcanza la celda objetivo.

Episodio 980: Se establece 27 como celda de inicio, y se toma como celda objetivo la 30.
La lista de siguientes celdas posibles es: [10, 12, 16, 20]
El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: 10.
Se actualiza el valor de Q[27][10] a 809.9999999999997.
Actualizamos la celda actual a 10.
La lista de siguientes celdas posibles es: [1, 7, 13, 19, 25, 27]
El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: 19.
Se actualiza el valor de Q[10][19] a 899.9999999999997.
Actualizamos la ce

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [777]:
print(Q)

 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 8.19000000e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.000

## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 con las recompensas asignadas debería ser (0 -> 5 -> 18 -> 21 -> 30).

In [778]:
inicio = 0
objetivo = 30
camino = []
camino.append(inicio)
actual = inicio
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
print(camino)


[0, 5, 18, 21, 30]


## Rendimiento

Se considerarán como medidas de rendimiento:
* La suma de todos los valores de Q divididos entre el máximo valor de Q multiplicados por 100.
* El tiempo total de la ejecución.

In [779]:
# Obtenemos el valor máximo de la matriz Q
maxQ = np.max(Q)
# Dividimos cada elemento de la matriz Q por el valor máximo y lo multiplicamos por 100
divQ = Q/maxQ*100
# Sumamos todos los elementos de la matriz Q
sumQ = divQ.sum()
#Imprimimos los resultados de rendimiento
print("El valor del rendimiento siguiendo la fórmula mencionada es: " + str(divQ.sum()))
print("El tiempo total de ejecución en segundos es: " + str(end - start))

El valor del rendimiento siguiendo la fórmula mencionada es: 4373.985252662909
El tiempo total de ejecución en segundos es: 1.6130003929138184


In [780]:
# Imprimimos la matriz normalizada
print(divQ)

0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 8.19000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.0000