### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

In [209]:
import numpy as np
import random
from random import randint

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero por defecto a utilizar, en este caso será el mismo que en la Fase 1

In [210]:
T = np.array([[8,7,6],
              [3,2,5],
              [0,1,4]])
print(T)

[[8 7 6]
 [3 2 5]
 [0 1 4]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero.

In [211]:
R = np.array([[-1,0,0,0,-1,-1,-1,-1,-1],
              [0,-1,0,0,0,0,-1,-1,-1],
              [0,0,-1,0,0,0,100,0,0],
              [0,0,0,-1,-1,-1,-1,0,0],
              [-1,0,0,-1,-1,0,-1,-1,-1],
              [-1,0,0,-1,0,-1,100,0,-1],
              [-1,-1,0,-1,-1,0,100,0,-1],
              [-1,-1,0,0,-1,0,100,-1,0],
              [-1,-1,0,0,-1,-1,-1,0,-1]])
print(R)

[[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]


## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [212]:
Q = np.zeros((9,9))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [213]:
inicio = 0
objetivo = 6
episodios = 10000
gamma = 0.8
epsilon = 1
alpha = 0.75
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")
print("El valor de épsilon es " + str(epsilon) + " y el de alpha es " + str(alpha) + ".")

La celda de inicio será la 0 y la celda objetivo será la 6.
El número de episodios será 100 y el factor de aprendizaje gamma es de 0.8.
El valor de épsilon es 1 y el de alpha es 0.99.


## Algoritmo
Incluimos, en este caso, las variables epsilon y alpha

In [2]:
rango = range(episodios)

for x in rango:
    inicio = randint(0, 8)
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    actual = inicio
    while actual != objetivo:
        posibles = []
        for y in range(9):
            if R[actual][y] == 0 or R[actual][y] == 100:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        # Implementación epsilon fase 2
        aleatorioEpsilon = random.uniform(0,1)

        # Si el valor aleatorio es menor que epsilon
        if aleatorioEpsilon < epsilon:
            # Elegimos aleatoriamente el estado siguiente
            aleatorioPosibles = randint(0,int(len(posibles)-1))
            aleatorio = posibles[aleatorioPosibles]
            print("El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: " + str(aleatorio) + ".")
        # Si el valor aleatorio es mayor que epsilon
        else:
            posiblesValor = []
            for posible in posibles:
                supuestosPosible = []
                # Analizamos cuales son las celdas viables segun la matriz R
                for aux in range(9):
                    if R[posible][aux] == 0 or R[posible][aux] == 100:
                        # Calculamos el valor de dicha celda en nuestra matriz Q
                        valor = Q[posible][aux]
                        supuestosPosible.append(valor)
                # Seleccionamos la celda con mayor valor en nuestra matriz
                maximoSupuestosPosible = max(supuestosPosible)
                posiblesValor.append(R[actual][posible] + gamma * maximoSupuestosPosible)
            aleatorio = posibles[np.argmax(posiblesValor)]
            print("El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: " + str(aleatorio) + ".")
        ##---------------------
        supuestos = []
        for z in range(9):
            if R[aleatorio][z] == 0 or R[aleatorio][z] == 100:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        maximoSupuestos = max(supuestos)
        # Actualizamos el valor de Q segun los estados seleccionados
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    # Actualizamos el valor de epsilon en base al alpha definido y repetimos la iteracion hasta el ultimo episodio
    epsilon = epsilon * alpha
    print("Se actualiza el valor de épsilon a " + str(epsilon) + ".")
    print("Se alcanza la celda objetivo.")

NameError: name 'episodios' is not defined

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [215]:
print(Q)

[[  0.  64.  80.  64.   0.   0.   0.   0.   0.]
 [ 64.   0.  80.  64.  64.  80.   0.   0.   0.]
 [ 64.  64.   0.  64.  64.  80. 100.  80.  64.]
 [ 64.  64.  80.   0.   0.   0.   0.  80.  64.]
 [  0.  64.  80.   0.   0.  80.   0.   0.   0.]
 [  0.  64.  80.   0.  64.   0. 100.  80.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  80.  64.   0.  80. 100.   0.  64.]
 [  0.   0.  80.  64.   0.   0.   0.  80.   0.]]


## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 debería ser 0, 2, 6.

In [216]:
inicio = 0
objetivo = 6
camino = []
camino.append(inicio)
actual = inicio
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
print(camino)


[0, 2, 6]
