### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

Random: para la generación de números aleatorios
Numpy: para poder trabajar con los tableros (matrices)

In [1]:
import numpy as np
from random import randint

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero descrito en el enunciado de la Fase 1.

In [2]:
T = np.array([[8,7,6],
              [3,2,5],
              [0,1,4]])
print(T)

[[8 7 6]
 [3 2 5]
 [0 1 4]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero, definido según el enunciado de la Fase 1.

In [3]:
R = np.array([[-1,0,0,0,-1,-1,-1,-1,-1],
              [0,-1,0,0,0,0,-1,-1,-1],
              [0,0,-1,0,0,0,100,0,0],
              [0,0,0,-1,-1,-1,-1,0,0],
              [-1,0,0,-1,-1,0,-1,-1,-1],
              [-1,0,0,-1,0,-1,100,0,-1],
              [-1,-1,0,-1,-1,0,100,0,-1],
              [-1,-1,0,0,-1,0,100,-1,0],
              [-1,-1,0,0,-1,-1,-1,0,-1]])
print(R)

[[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]


## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [4]:
Q = np.zeros((9,9))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [5]:
inicio = 0
objetivo = 6
episodios = 10000
gamma = 0.8
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")

La celda de inicio será la 0 y la celda objetivo será la 6.
El número de episodios será 10000 y el factor de aprendizaje gamma será de 0.8.


## Algoritmo
Definimos el algoritmo en base al pseudo-código que aparece en el enunciado del trabajo.

In [ ]:
# Asignamos el número de episodios del algoritmo en base al valor definido
rango = range(episodios)

# Definimos el bucle del algoritmo que se irá ejecutando hasta que finalicen los episodios
for x in rango:
    # Iniciamos en una casilla aleatoria del tablero
    inicio = randint(0, 8)
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    # Establecemos que el episodio en ejecucion comience en la casilla de inicio 
    actual = inicio
    # Definimos el bucle que se ejecutara hasta que se llegue a la celda objetivo
    while actual != objetivo:
        # Inicializamos una lista donde añadimos las posibles celdas para el siguiente estado
        # en base a lo definido en la matriz R 
        posibles = []
        for y in range(9):
            if R[actual][y] == 0 or R[actual][y] == 100:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        # Elegimos aleatoriamente, entre las celdas posibles, la siguiente
        aleatorioPosibles = randint(0,int(len(posibles)-1))
        aleatorio = posibles[aleatorioPosibles]
        print("Se elige aleatoriamente la celda " + str(aleatorio) + ".")
        # Inicializamos una lista donde evaluamos los posibles siguientes estados (en base a la matriz Q)
        supuestos = []
        for z in range(9):
            if R[aleatorio][z] == 0 or R[aleatorio][z] == 100:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        # Seleccionamos el mayor valor de todos los posibles supuestos
        maximoSupuestos = max(supuestos)
        # Actualizamos la matriz Q con el maximo localizado
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        # Pasamos a la celda elegida aleatoriamente y volvemos a iterar
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    print("Se alcanza la celda objetivo.")

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [7]:
print(Q)

[[  0.  64.  80.  64.   0.   0.   0.   0.   0.]
 [ 64.   0.  80.  64.  64.  80.   0.   0.   0.]
 [ 64.  64.   0.  64.  64.  80. 100.  80.  64.]
 [ 64.  64.  80.   0.   0.   0.   0.  80.  64.]
 [  0.  64.  80.   0.   0.  80.   0.   0.   0.]
 [  0.  64.  80.   0.  64.   0. 100.  80.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  80.  64.   0.  80. 100.   0.  64.]
 [  0.   0.  80.  64.   0.   0.   0.  80.   0.]]


## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 debería ser 0, 2, 6.

In [8]:
inicio = 0
objetivo = 6
camino = []
# Establecemos como primera casilla la definida como inicio
camino.append(inicio)
actual = inicio
# Hacemos un bucle que irá seleccionando como siguiente celda la que mayor recompensa obtenga segun
# nuestra matriz Q calculada con nuestro algoritmo anteriormente
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
# Mostramos el resultado obtenido con el bucle
print(camino)


[0, 2, 6]
