### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

In [83]:
import time
import numpy as np
import random
from random import randint
np.set_printoptions(threshold=sys.maxsize)

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero por defecto a utilizar, en este caso será el mismo que en la Fase 1

In [86]:
T = np.array([[8,7,6],
              [3,2,5],
              [0,1,4]])
print(T)

[[8 7 6]
 [3 2 5]
 [0 1 4]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero.

In [89]:
R = np.array([[-1,0,0,0,-1,-1,-1,-1,-1],
              [0,-1,0,0,0,0,-1,-1,-1],
              [0,0,-1,0,0,0,100,0,0],
              [0,0,0,-1,-1,-1,-1,0,0],
              [-1,0,0,-1,-1,0,-1,-1,-1],
              [-1,0,0,-1,0,-1,100,0,-1],
              [-1,-1,0,-1,-1,0,100,0,-1],
              [-1,-1,0,0,-1,0,100,-1,0],
              [-1,-1,0,0,-1,-1,-1,0,-1]])
print(R)

[[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]


## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [92]:
Q = np.zeros((9,9))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [95]:
inicio = 0
objetivo = 6
episodios = 1000
gamma = 0.9
epsilon = 1
alpha = 1
tamano = 9 # Número total de casillas de la matriz
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")
print("El valor de épsilon es " + str(epsilon) + " y el de alpha es " + str(alpha) + ".")

La celda de inicio será la 0 y la celda objetivo será la 6.
El número de episodios será 1000 y el factor de aprendizaje gamma es de 0.9.
El valor de épsilon es 1 y el de alpha es 1.


## Algoritmo
Incluimos, en este caso, las variables epsilon y alpha

In [97]:
#Iniciamos el contador de tiempo para medidas de rendimiento
start = time.time()

rango = range(episodios)

for x in rango:
    inicio = randint(0, tamano-1)
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    actual = inicio
    while actual != objetivo:
        posibles = []
        for y in range(tamano):
            if R[actual][y] != -1:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        # Implementación epsilon fase 2
        aleatorioEpsilon = random.uniform(0,1)

        # Si el valor aleatorio es menor que epsilon
        if aleatorioEpsilon < epsilon:
            # Elegimos aleatoriamente el estado siguiente
            aleatorioPosibles = randint(0,int(len(posibles)-1))
            aleatorio = posibles[aleatorioPosibles]
            print("El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: " + str(aleatorio) + ".")
        # Si el valor aleatorio es mayor que epsilon
        else:
            posiblesValor = []
            for posible in posibles:
                supuestosPosible = []
                # Analizamos cuales son las celdas viables segun la matriz R
                for aux in range(tamano):
                    if R[posible][aux] != -1:
                        # Calculamos el valor de dicha celda en nuestra matriz Q
                        valor = Q[posible][aux]
                        supuestosPosible.append(valor)
                # Seleccionamos la celda con mayor valor en nuestra matriz
                maximoSupuestosPosible = max(supuestosPosible)
                posiblesValor.append(R[actual][posible] + gamma * maximoSupuestosPosible)
            aleatorio = posibles[np.argmax(posiblesValor)]
            print("El número generado aleatoriamente es mayor o igual que épsilon, se elige el siguiente estado con más valor entre los posibles: " + str(aleatorio) + ".")
        ##---------------------
        supuestos = []
        for z in range(tamano):
            if R[aleatorio][z] != -1:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        maximoSupuestos = max(supuestos)
        # Actualizamos el valor de Q segun los estados seleccionados
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    # Actualizamos el valor de Q para la celda objetivo
    Q[actual][actual] = R[actual][actual] + gamma * Q[actual][actual]
    # Actualizamos el valor de epsilon en base al alpha definido y repetimos la iteracion hasta el ultimo episodio
    epsilon = epsilon * alpha
    print("Se actualiza el valor de épsilon a " + str(epsilon) + ".")
    print("Se alcanza la celda objetivo.")

#Finalizamos el contador de tiempo para medidas de rendimiento
end = time.time()

1] a 809.9999999999997.
Actualizamos la celda actual a 1.
La lista de siguientes celdas posibles es: [0, 2, 3, 4, 5]
El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: 3.
Se actualiza el valor de Q[1][3] a 809.9999999999997.
Actualizamos la celda actual a 3.
La lista de siguientes celdas posibles es: [0, 1, 2, 7, 8]
El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: 0.
Se actualiza el valor de Q[3][0] a 809.9999999999997.
Actualizamos la celda actual a 0.
La lista de siguientes celdas posibles es: [1, 2, 3]
El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: 1.
Se actualiza el valor de Q[0][1] a 809.9999999999997.
Actualizamos la celda actual a 1.
La lista de siguientes celdas posibles es: [0, 2, 3, 4, 5]
El número generado aleatoriamente es menor que épsilon, el siguiente estado se elige al azar: 5.
Se actualiza el valor de Q[1][5] a 899.9999999999997.
Actual

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [99]:
print(Q)

[[   0.  810.  900.  810.    0.    0.    0.    0.    0.]
 [ 810.    0.  900.  810.  810.  900.    0.    0.    0.]
 [ 810.  810.    0.  810.  810.  900. 1000.  900.  810.]
 [ 810.  810.  900.    0.    0.    0.    0.  900.  810.]
 [   0.  810.  900.    0.    0.  900.    0.    0.    0.]
 [   0.  810.  900.    0.  810.    0. 1000.  900.    0.]
 [   0.    0.    0.    0.    0.    0. 1000.    0.    0.]
 [   0.    0.  900.  810.    0.  900. 1000.    0.  810.]
 [   0.    0.  900.  810.    0.    0.    0.  900.    0.]]


## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 debería ser (0 -> 2 -> 6).

In [101]:
inicio = 0
objetivo = 6
camino = []
camino.append(inicio)
actual = inicio
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
print(camino)


[0, 2, 6]


## Rendimiento

Se considerarán como medidas de rendimiento:
* La suma de todos los valores de Q divididos entre el máximo valor de Q multiplicados por 100.
* El tiempo total de la ejecución.

In [103]:
# Obtenemos el valor máximo de la matriz Q
maxQ = np.max(Q)
# Dividimos cada elemento de la matriz Q por el valor máximo y lo multiplicamos por 100
divQ = Q/maxQ*100
# Sumamos todos los elementos de la matriz Q
sumQ = divQ.sum()
#Imprimimos los resultados de rendimiento
print("El valor del rendimiento siguiendo la fórmula mencionada es: " + str(divQ.sum()))
print("El tiempo total de ejecución en segundos es: " + str(end - start))

El valor del rendimiento siguiendo la fórmula mencionada es: 3289.0
El tiempo total de ejecución en segundos es: 3.769598960876465


In [105]:
# Imprimimos la matriz normalizada
print(divQ)

[[  0.  81.  90.  81.   0.   0.   0.   0.   0.]
 [ 81.   0.  90.  81.  81.  90.   0.   0.   0.]
 [ 81.  81.   0.  81.  81.  90. 100.  90.  81.]
 [ 81.  81.  90.   0.   0.   0.   0.  90.  81.]
 [  0.  81.  90.   0.   0.  90.   0.   0.   0.]
 [  0.  81.  90.   0.  81.   0. 100.  90.   0.]
 [  0.   0.   0.   0.   0.   0. 100.   0.   0.]
 [  0.   0.  90.  81.   0.  90. 100.   0.  81.]
 [  0.   0.  90.  81.   0.   0.   0.  90.   0.]]
