### Importaciones
Necesarias para el correcto funcionamiento del proyecto.

Random: para la generación de números aleatorios
Numpy: para poder trabajar con los tableros (matrices)

In [142]:
import time
import numpy as np
import random
from random import randint
np.set_printoptions(threshold=sys.maxsize)

# Aprendizaje por Refuerzo
## Tablero
Definimos el tablero descrito en el enunciado de la Fase 1.

In [143]:
T = np.array([[8,7,6],
              [3,2,5],
              [0,1,4]])
print(T)

[[8 7 6]
 [3 2 5]
 [0 1 4]]


## Matriz R
Definimos la matriz R calculada a partir de los posibles movimientos del tablero, definido según el enunciado de la Fase 1.

In [144]:
R = np.array([[-1,0,0,0,-1,-1,-1,-1,-1],
              [0,-1,0,0,0,0,-1,-1,-1],
              [0,0,-1,0,0,0,100,0,0],
              [0,0,0,-1,-1,-1,-1,0,0],
              [-1,0,0,-1,-1,0,-1,-1,-1],
              [-1,0,0,-1,0,-1,100,0,-1],
              [-1,-1,0,-1,-1,0,100,0,-1],
              [-1,-1,0,0,-1,0,100,-1,0],
              [-1,-1,0,0,-1,-1,-1,0,-1]])
print(R)

[[ -1   0   0   0  -1  -1  -1  -1  -1]
 [  0  -1   0   0   0   0  -1  -1  -1]
 [  0   0  -1   0   0   0 100   0   0]
 [  0   0   0  -1  -1  -1  -1   0   0]
 [ -1   0   0  -1  -1   0  -1  -1  -1]
 [ -1   0   0  -1   0  -1 100   0  -1]
 [ -1  -1   0  -1  -1   0 100   0  -1]
 [ -1  -1   0   0  -1   0 100  -1   0]
 [ -1  -1   0   0  -1  -1  -1   0  -1]]


## Matriz Q
Inicializamos Q como una matriz de 0s del mismo tamaño que la matriz R.

In [145]:
Q = np.zeros((9,9))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Parámetros
Apartado para configurar los distintos parámetros que utilizará el algoritmo.

In [146]:
inicio = 0
objetivo = 6
episodios = 1000
gamma = 0.9
tamano = 9 # Número total de casillas de la matriz
print("La celda de inicio será la " + str(inicio) + " y la celda objetivo será la " + str(objetivo) +".")
print("El número de episodios será " + str(episodios) + " y el factor de aprendizaje gamma es de " + str(gamma) + ".")

La celda de inicio será la 0 y la celda objetivo será la 6.
El número de episodios será 1000 y el factor de aprendizaje gamma es de 0.9.


## Algoritmo
Definimos el algoritmo en base al pseudo-código que aparece en el enunciado del trabajo.

In [147]:
#Iniciamos el contador de tiempo para medidas de rendimiento
start = time.time()

# Asignamos el número de episodios del algoritmo en base al valor definido
rango = range(episodios)

# Definimos el bucle del algoritmo que se irá ejecutando hasta que finalicen los episodios
for x in rango:
    # Iniciamos en una casilla aleatoria del tablero
    inicio = randint(0, (tamano-1))
    print("\nEpisodio " + str(x+1) + ": Se establece " + str(inicio) + " como celda de inicio, y se toma como celda objetivo la " + str(objetivo) + ".")
    # Establecemos que el episodio en ejecucion comience en la casilla de inicio 
    actual = inicio
    # Definimos el bucle que se ejecutara hasta que se llegue a la celda objetivo
    while actual != objetivo:
        # Inicializamos una lista donde añadimos las posibles celdas para el siguiente estado
        # en base a lo definido en la matriz R 
        posibles = []
        for y in range(tamano):
            if R[actual][y] != -1:
                posibles.append(y)
        print("La lista de siguientes celdas posibles es: " + str(posibles))
        # Elegimos aleatoriamente, entre las celdas posibles, la siguiente
        aleatorioPosibles = randint(0,int(len(posibles)-1))
        aleatorio = posibles[aleatorioPosibles]
        print("Se elige aleatoriamente la celda " + str(aleatorio) + ".")
        # Inicializamos una lista donde evaluamos los posibles siguientes estados (en base a la matriz Q)
        supuestos = []
        for z in range(tamano):
            if R[aleatorio][z] != -1:
                calculo = Q[aleatorio][z]
                supuestos.append(calculo)
        # Seleccionamos el mayor valor de todos los posibles supuestos
        maximoSupuestos = max(supuestos)
        # Actualizamos la matriz Q con el maximo localizado
        Q[actual][aleatorio] = R[actual][aleatorio] + gamma * maximoSupuestos
        print("Se actualiza el valor de Q[" + str(actual) + "]" + "[" + str(aleatorio) + "] a " + str(Q[actual][aleatorio]) + "." )
        # Pasamos a la celda elegida aleatoriamente y volvemos a iterar
        actual = aleatorio
        print("Actualizamos la celda actual a " + str(actual) + ".")
    # Actualizamos el valor de Q para la celda objetivo
    Q[actual][actual] = R[actual][actual] + gamma * Q[actual][actual]
    print("Se alcanza la celda objetivo.")

#Finalizamos el contador de tiempo para medidas de rendimiento
end = time.time()

999999997.
Actualizamos la celda actual a 2.
La lista de siguientes celdas posibles es: [0, 1, 3, 4, 5, 6, 7, 8]
Se elige aleatoriamente la celda 3.
Se actualiza el valor de Q[2][3] a 809.9999999999997.
Actualizamos la celda actual a 3.
La lista de siguientes celdas posibles es: [0, 1, 2, 7, 8]
Se elige aleatoriamente la celda 1.
Se actualiza el valor de Q[3][1] a 809.9999999999997.
Actualizamos la celda actual a 1.
La lista de siguientes celdas posibles es: [0, 2, 3, 4, 5]
Se elige aleatoriamente la celda 3.
Se actualiza el valor de Q[1][3] a 809.9999999999997.
Actualizamos la celda actual a 3.
La lista de siguientes celdas posibles es: [0, 1, 2, 7, 8]
Se elige aleatoriamente la celda 0.
Se actualiza el valor de Q[3][0] a 809.9999999999997.
Actualizamos la celda actual a 0.
La lista de siguientes celdas posibles es: [1, 2, 3]
Se elige aleatoriamente la celda 2.
Se actualiza el valor de Q[0][2] a 899.9999999999997.
Actualizamos la celda actual a 2.
La lista de siguientes celdas posible

## Matriz Q resultante
Así queda la matriz Q después de completar todos los episodios.

In [148]:
print(Q)

[[   0.  810.  900.  810.    0.    0.    0.    0.    0.]
 [ 810.    0.  900.  810.  810.  900.    0.    0.    0.]
 [ 810.  810.    0.  810.  810.  900. 1000.  900.  810.]
 [ 810.  810.  900.    0.    0.    0.    0.  900.  810.]
 [   0.  810.  900.    0.    0.  900.    0.    0.    0.]
 [   0.  810.  900.    0.  810.    0. 1000.  900.    0.]
 [   0.    0.    0.    0.    0.    0. 1000.    0.    0.]
 [   0.    0.  900.  810.    0.  900. 1000.    0.  810.]
 [   0.    0.  900.  810.    0.    0.    0.  900.    0.]]


## Comprobante
Se comprueba que una vez entrenada la matriz Q el agente encuentra el mejor camino, que, por ejemplo partiendo de 0 debería ser (0 -> 2 -> 6).

In [149]:
inicio = 0
objetivo = 6
camino = []
# Establecemos como primera casilla la definida como inicio
camino.append(inicio)
actual = inicio
# Hacemos un bucle que irá seleccionando como siguiente celda la que mayor recompensa obtenga segun
# nuestra matriz Q calculada con nuestro algoritmo anteriormente
while actual != objetivo:
    siguiente = np.argmax(Q[actual])
    camino.append(siguiente)
    actual = siguiente
# Mostramos el resultado obtenido con el bucle
print(camino)


[0, 2, 6]


In [150]:
## Rendimiento

Se considerarán como medidas de rendimiento:
* La suma de todos los valores de Q divididos entre el máximo valor de Q multiplicados por 100.
* El tiempo total de la ejecución.


SyntaxError: invalid syntax (<ipython-input-150-d1e332516ea1>, line 3)

In [151]:
# Obtenemos el valor máximo de la matriz Q
maxQ = np.max(Q)
# Dividimos cada elemento de la matriz Q por el valor máximo y lo multiplicamos por 100
divQ = Q/maxQ*100
# Sumamos todos los elementos de la matriz Q
sumQ = divQ.sum()
#Imprimimos los resultados de rendimiento
print("El valor del rendimiento siguiendo la fórmula mencionada es: " + str(divQ.sum()))
print("El tiempo total de ejecución en segundos es: " + str(end - start))

El valor del rendimiento siguiendo la fórmula mencionada es: 3289.0
El tiempo total de ejecución en segundos es: 3.560783624649048


In [152]:
# Imprimimos la matriz normalizada
print(divQ)

[[  0.  81.  90.  81.   0.   0.   0.   0.   0.]
 [ 81.   0.  90.  81.  81.  90.   0.   0.   0.]
 [ 81.  81.   0.  81.  81.  90. 100.  90.  81.]
 [ 81.  81.  90.   0.   0.   0.   0.  90.  81.]
 [  0.  81.  90.   0.   0.  90.   0.   0.   0.]
 [  0.  81.  90.   0.  81.   0. 100.  90.   0.]
 [  0.   0.   0.   0.   0.   0. 100.   0.   0.]
 [  0.   0.  90.  81.   0.  90. 100.   0.  81.]
 [  0.   0.  90.  81.   0.   0.   0.  90.   0.]]
